Repository rw-moore/SciLO, pull requests merged in 2019-05, with the labels that each got.

#11 feat: add grading system
  polls/controller/__init__.py
  polls/controller/grading_controller.py
  polls/migrations/0014_response_weight.py
  polls/models/algorithm.py
  polls/models/question.py
  polls/models/response.py
  polls/script/query/__init__.py
  polls/script/query/grading.py
  polls/views/response_attempt_view.py
Labels: enhancement

#16 Feat: pylint
  .pylintrc
  .vscode/settings.json
  azure-piplines.yml
  polls/admin.py
  polls/controller/__init__.py
  polls/controller/grading_controller.py
  polls/migrations/0015_response_grade_policy.py
  polls/models/__init__.py
  polls/models/algorithm.py
  polls/models/answer.py
  polls/models/category.py
  polls/models/gradepolicy.py
  polls/models/question.py
  polls/models/quiz.py
  polls/models/response.py
  polls/models/user.py
  polls/models/utils.py
  polls/models/variable.py
  polls/script/execute/mathexpress.py
  polls/script/execute/numerical.py
  polls/script/query/grading.py
  polls/serializers/__init__.py
  polls/serializers/category.py
  polls/serializers/question.py
  polls/serializers/question_attempt.py
  polls/serializers/quiz.py
  polls/serializers/quiz_attempt.py
  polls/serializers/response.py
  polls/serializers/response_attempt.py
  polls/serializers/user.py
  polls/serializers/utils.py
  polls/views/__init__.py
  polls/views/category_views.py
  polls/views/question_attempt_view.py
  polls/views/question_views.py
  polls/views/quiz_attempt_views.py
  polls/views/quiz_views.py
  polls/views/response_attempt_view.py
  polls/views/response_views.py
  polls/views/user_views.py
  requirements.txt
Labels: bug, enhancement

#39 Frontend init
  frontend/.gitignore
  frontend/README.md
  frontend/config-overrides.js
  frontend/config/theme.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/components/QuestionBankTable/index.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/layouts/BasicLayout/index.css
  frontend/src/layouts/BasicLayout/index.js
  frontend/src/layouts/SideNav/index.css
  frontend/src/layouts/SideNav/index.js
  frontend/src/layouts/SketchQuestionBank.js
  frontend/src/logo.svg
  frontend/src/mocks/QuestionBankTable.js
  frontend/src/serviceWorker.js
Labels: Release 1

#42 Feat/frontend/question
  frontend/config-overrides.js
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/DefaultQuestionTypes/InputField.js
  frontend/src/components/DefaultQuestionTypes/MultipleChoice.js
  frontend/src/components/QuestionPreviews/BasicFrame.js
  frontend/src/components/forms/CreateQuestionForm.js
  frontend/src/config/theme.json
  frontend/src/layouts/BasicLayout/index.js
  frontend/src/layouts/SideNav/index.css
  frontend/src/mocks/Questions.js
  frontend/src/mocks/Tags.js
  frontend/src/pages/CreateQuestions/index.js
  frontend/src/pages/QuestionBankTable/index.js
Labels: Release 1

#47 Fix: response name and API tests
  api/urls.py
  polls/migrations/0026_auto_20190530_0220.py
  polls/models/response.py
  polls/serializers/question.py
  polls/views/question_views.py
Labels: bug, enhancement
