Repository rw-moore/SciLO, pull requests merged in 2019-06, with the labels that each got.

#52 Feat/frontend/question checkpoint
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/components/DefaultQuestionTypes/InputField.js
  frontend/src/components/DefaultQuestionTypes/MultipleChoice.js
  frontend/src/components/Forms/CreateQuestionForm.js
  frontend/src/components/QuestionPreviews/BasicFrame.js
  frontend/src/components/Variables/CreateVariableModal.js
  frontend/src/components/forms/CreateQuestionForm.js
  frontend/src/index.css
  frontend/src/layouts/BasicLayout/index.js
  frontend/src/mocks/Questions.js
  frontend/src/networks/Endpoints.js
  frontend/src/networks/PostQuestion.js
  frontend/src/pages/CreateQuestions/index.js
  frontend/src/utils/FractionDisplay.js
  frontend/src/utils/RandomID.js
Labels: Release 1

#54 Fix: post a question http request
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Forms/CreateQuestionForm.js
  frontend/src/layouts/BasicLayout/index.js
  frontend/src/networks/GetQuestions.js
  frontend/src/networks/PostQuestion.js
  frontend/src/pages/QuestionBankTable/index.js
Labels: Release 1, bug

#60 Fix: tags list
  polls/models/tag.py
  polls/views/tag_views.py
Labels: bug

#62 Fix: navigation bar collapsing not behaves properly
  frontend/src/layouts/BasicLayout/index.js
  frontend/src/layouts/SideNav/index.css
Labels: Release 1, bug

#66 Feat/questionbank/table
  frontend/package.json
  frontend/public/index.html
  frontend/src/components/Forms/CreateQuestionForm.js
  frontend/src/components/Forms/GetTagsSelectBar.js
  frontend/src/components/QuestionPreviews/QuickLook.js
  frontend/src/components/Users/UserIcon.js
  frontend/src/components/Variables/CreateVariableModal.js
  frontend/src/layouts/BasicLayout/index.css
  frontend/src/layouts/BasicLayout/index.js
  frontend/src/layouts/SideNav/index.js
  frontend/src/networks/PutQuestion.js
  frontend/src/pages/CreateQuestions/index.js
  frontend/src/pages/Exceptions/404.js
  frontend/src/pages/QuestionBankTable/index.css
  frontend/src/pages/QuestionBankTable/index.js
Labels: Release 1

#67 feat: add script editor support
  frontend/package.json
  frontend/src/components/Variables/CodeEditor.js
  frontend/src/components/Variables/CreateVariableModal.js
Labels: Release 1

#69 Feat/question/patch0621
  frontend/public/index.html
  frontend/src/pages/QuestionBankTable/index.js
Labels: Release 1
